### ISSUE TITLE
Apostrophes create weird breaks in lines

### ISSUE THREAD

**Issue by jake-bladt** [xiaoheiAh/hugo-theme-pure#10]
On the text, "I did note that, out of the box, LINQ’s IEnumerable.Any doesn’t do any optimization," both apostrophes generate weird spacing in the output text.

Looking at the underlying generated html, the spacing appears to be caused by a <t> element being generated.

**Comment by xiaoheiAh** [comment]
Hi @jake-bladt 
Could you upload a screenshot?  I have not reproduced this question. Here is what I am rendering here. 
![image](https://user-images.githubusercontent.com/27981726/68637713-735df180-053a-11ea-8d8b-429d5e93b72e.png)

**Comment by jake-bladt** [comment]
Here is the generated html:

```<p>I did note that, out of the box, LINQ&rsquo;s IEnumerable.Any<T> doesn&rsquo;t do any optimization (nor should it,) but it did mean that comparing two lists of 50,000 items for up to six matching properties required ~3-10 billion string equality comparisons and takes about a minute. I will eventually have to reoptimize if the project grows much larger.</p>```

The screen shot is [here](https://imgur.com/gallery/AHK3BW7).

**Comment by jake-bladt** [comment]
A debugging note: I thought this might be a problem with the unescaped IEnumerable<T>.Any in the text, but the problem occurs throughout the page, even when I escape the term to "IEnumerable&lt;T&gt;.Any."

**Comment by xiaoheiAh** [comment]
Sorry @jake-bladt 
I still didn't reproduce it, but I found that `<T>` disappeared when rendering, and you can use this way to avoid it if you like : `IEnumerable<T>.Any`

**Comment by jake-bladt** [comment]
I will continue to investigate and let you know if I find anything, then.
