### ISSUE TITLE
Shortcode broken and some customization problems

### ISSUE THREAD

**Issue by Nyte-BK201** [xiaoheiAh/hugo-theme-pure#11]
New to hugo. I met problems in such:
1/ Instagram API is broken with
`Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BGvuInzyFAe/&hidecaption=1": Get https://api.instagram.com/oembed/?url=https://instagram.com/p/BGvuInzyFAe/&hidecaption=1`
Also the twitter/ Vimeo not working( only youtube still working)
I want to fix it but I can not find option/ code. ( I know it is shortcode not working but not knowing how to fix )

2/ How can I change the font size in article pages?
I want my article's main body font much larger (including markdown headings/ quote/ code fence etc. Is it possible in this theme?

3/ How can I disable tags globally?
I have disabled tags in the two sidebars, I want to disable it below the title.

**Comment by Nyte-BK201** [comment]
我把页面托管在github pages上，还遇到了首个文章显示不正确的问题。
URL: http://nyte.xyz/posts/    以及 http://nyte.xyz/categories/  出现的第一篇文章显示都不正确。
我检查了CSS已经正确加载，HTML上面和下面也没有区别，不知道为什么第一个会出错。
在本地使用hugo server访问localhost一切正常，没有出现这个问题。

**Comment by xiaoheiAh** [comment]
> 1/ Instagram API is broken with
Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BGvuInzyFAe/&hidecaption=1": Get https://api.instagram.com/oembed/?url=https://instagram.com/p/BGvuInzyFAe/&hidecaption=1
Also the twitter/ Vimeo not working( only youtube still working)
I want to fix it but I can not find option/ code. ( I know it is shortcode not working but not knowing how to fix )

国内被 ban 了,用外网服务器编译的话就没问题,目前也没有找到什么好的方法.

> 2/ How can I change the font size in article pages?

可以自行fork一份,debug 源代码修改 `style.css` 中对应项

> 3/ How can I disable tags globally?

fork后编辑 `layouts/partials/article.html`. 注释掉你不想要代码.
line 13-15之间:
```html
      <div class="article-meta">
        {{ .Scratch.Set "class_name" "article-date" }}
        {{- partial "post/date.html" . }}
        {{- partial "post/category.html" . }}
        {{- partial "post/tag.html" . }}
        {{- partial "post/pv.html" . }}
        <span class="post-comment"><i class="icon icon-comment"></i> <a href="{{ .RelPermalink }}#comments"
            class="article-comment-link">{{T "article_comments" }}</a></span>
        {{- partial "post/wc.html" . }}
      </div>
```

> 我把页面托管在github pages上，还遇到了首个文章显示不正确的问题。
URL: http://nyte.xyz/posts/ 以及 http://nyte.xyz/categories/ 出现的第一篇文章显示都不正确。
我检查了CSS已经正确加载，HTML上面和下面也没有区别，不知道为什么第一个会出错。
在本地使用hugo server访问localhost一切正常，没有出现这个问题。

想看下你写的脚本, 我还没有遇到过这个问题

**Comment by Nyte-BK201** [comment]
之前没注意，原来demo里也有这个问题，我以为是我配置问题。
https://themes.gohugo.io//theme/hugo-theme-pure/tags 
`#markdown` 这个tag里markdown syntax guide显示不正确（和我正好相反，我是archive 里显示成tag，而这个是tag中显示成archive ）和我显示错误的竟然是同一篇文章。

**Comment by Nyte-BK201** [comment]
这应该是个tag的bug，所有posts都不使用tag就没有问题了。
