### ISSUE TITLE
Icons padding issue.

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#15]
Icons do not seem to have any sort of padding for me and are clinging to the text adjacent to it.
![Icon](https://i.postimg.cc/wxLTp4sp/icons-hugo-theme.png)

**Comment by xiaoheiAh** [comment]
hi @udit-001 
there have padding in my [example website](https://xiaohei.im/hugo-theme-pure/)
![image](https://user-images.githubusercontent.com/27981726/69125062-e8539d00-0adf-11ea-977e-e61d7583fc32.png) 
compare our css style diff  in your console?

**Comment by udit-001** [comment]
It's exactly the same :sweat:

**Comment by udit-001** [comment]
I think it's worth mentioning that this only seems to be the problem when I deploy it on Netlify, and not on my local server. 

So, to fix it I added some CSS on my own over here https://github.com/xiaoheiAh/hugo-theme-pure/blob/master/static/css/style.css#L5151,

which was :
`padding-right: 3px;`

This seems to fix it for me.

**Comment by xiaoheiAh** [comment]
okay~ I'll close this issue
