### ISSUE TITLE
Upgrade jquery from deprecated version 1.12.x to 3.4.1.

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#18]
The theme uses an outdated version of jquery which is now considered to have security issues. We should migrate to a supported version (3.4.1). You can use [jquery-migrate](https://github.com/jquery/jquery-migrate), I have already tested it though and it doesn't issue any warnings, if you'd like, I can send in a pull request making the suggested changes.

**Comment by xiaoheiAh** [comment]
okay~ please send a pr~Has padding issue been solved?

**Comment by udit-001** [comment]
I just sent a PR for this #19, please check it out!

**Comment by xiaoheiAh** [comment]
good job~ 👍 😄

**Comment by xiaoheiAh** [comment]
if you have some other idea or find some bug, please let me know or just send me a pr.Thanks for your contribution. Have a good day~
