### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#21]
When I went through the files I saw a 404.html file but it didn't seem to have anything it it, do you have any plans on adding a 404 page to this theme?

**Comment by xiaoheiAh** [comment]
currently no plans.but we can implement it like index.html. would you like to add some style? I'm not good at css/html~

**Comment by udit-001** [comment]
yeah, so I took a look at the hexo theme that this theme was inspired by, here's how it's 404 page looks like : https://blog.cofess.com/wha

Seems to me it's just the post page, but with changed headings and content, can this be done?

**Comment by xiaoheiAh** [comment]
this is hexo theme 404 page source code. the js link is a charitable project but not work on that page.
```html
---
title: 404 Not Found：该页无法显示
toc: false
comments: false
permalink: /404
---
<script type="text/javascript" src="//www.qq.com/404/search_children.js" charset="utf-8" homePageUrl="<%- config.url %>" homePageName="回到我的主页"></script>
```
my suggestion is edit 404.html in our project like index.html use hugo block syntax. And do whatever you want~
```html
{{- define "content"}}
css/html you want to add~
{{- end }}
```

**Comment by udit-001** [comment]
Alright, I'll try it out, can you point me to the template file that is used to generate this page : https://xiaohei.im/hugo-theme-pure/2019/11/replication/

**Comment by xiaoheiAh** [comment]
this is what you need to develop: https://github.com/xiaoheiAh/hugo-theme-pure/blob/master/layouts/404.html
this is a reference: https://github.com/xiaoheiAh/hugo-theme-pure/blob/master/layouts/index.html

**Comment by udit-001** [comment]
This is what I created

![404](https://i.postimg.cc/qqg5xkZR/404.png)

What do you think?

**Comment by xiaoheiAh** [comment]
it seems look good~you can send a pr~

**Comment by udit-001** [comment]
@xiaoheiAh I just sent a PR #28, please check it out!

**Comment by xiaoheiAh** [comment]
already merge and add Chinese translation
