### ISSUE TITLE
MathJax config needs to be added.

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#24]
So there are some basic settings that need to be configured for MathJax to run on production, I took a look at the hugo [docs](https://gohugo.io/content-management/formats/#issues-with-markdown), the major setting that needs to be added is the support for mmark files :

```html
<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
              showMathMenu: false, //disables context menu
              tex2jax: {
              inlineMath: [ ['$','$'], ['\\(','\\)'] ]
             }
      });
</script>
```

**Comment by xiaoheiAh** [comment]
I'll fix it.
