### ISSUE TITLE
Please specify the steps to migrate from one theme to this

### ISSUE THREAD

**Issue by shashank-k** [xiaoheiAh/hugo-theme-pure#3]
I liked this theme very much. I would like to migrate from another theme to this. I request you to specify the steps in Readme.md

**Comment by xiaoheiAh** [comment]
hello @shashank-k 
thanks for your appreciate, it means a lot to me.
if you only want to change your theme, and migrate your blog posts to this theme, you can specify your `config.yml` and static resources  arrcording [README.md](https://github.com/xiaoheiAh/hugo-theme-pure/blob/master/README.md) .
if you want to customize, i'll update project layout later in README, and i'm glad to you can contribute to it~ 😄
