### ISSUE TITLE
Post nav string problem.

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#33]
Referring to the following code:
 
The nav links have their strings swapped, the text should be as follows: 
- Prev arrow should have the string 'nav_older'
- Next arrow should have the string 'nav_newer'

**Comment by xiaoheiAh** [comment]
you can give a patch~

**Comment by udit-001** [comment]
@xiaoheiAh I just sent a PR #34, please check!

**Comment by udit-001** [comment]
Merged! #34
