### ISSUE TITLE
Add support for choosing syntax highlighting languages.

### ISSUE THREAD

**Issue by udit-001** [xiaoheiAh/hugo-theme-pure#36]
I was wondering about how should we implement this?

**Comment by xiaoheiAh** [comment]
@udit-001 
Just do this [PR](https://github.com/xiaoheiAh/hugo-theme-pure/pull/17) work.And add corresponding params in config.yml.

**Comment by udit-001** [comment]
No I was wondering, that do we need post wise options as well?

like the site wide config it would be:
`hightlightjs:
  enable: true
  langs: ["python", "javascript"]
`

and for post, the config would be:
`syntax : ["python", "javascript"]`

**Comment by xiaoheiAh** [comment]
it's too detailed so that i don't think it's useful.Just give a wide config: `langs:["python","javascript"]`

**Comment by udit-001** [comment]
@xiaoheiAh I created a PR, for this #39, please check out!
