### ISSUE TITLE
math rendering?

### ISSUE THREAD

**Issue by cani-venatici** [xiaoheiAh/hugo-theme-pure#37]
How do you set up math rendering??

```
hugo new site folder
cd folder
git clone <repo> ./themes/pure
```
copied config.yml from exampleSite

```
hugo new posts/test.mmark
echo \$\$a+b=c\$\$ >> ./content/posts/test.mmark
hugo server -D
```
but math renders as `\(a+b=c\)`

Also `/layouts/partials/math.html` in the repo calls mathjax instead of katex, contrary to what [instructions](https://themes.gohugo.io//theme/hugo-theme-pure/post/math-typesetting/) say.

Am I missing something?

**Comment by xiaoheiAh** [comment]
Already fixed.Please pull latest update.

**Comment by xiaoheiAh** [comment]
hi @cani-venatici 
if this pr has solved your issue, please let me know or just close this issue~thanks
