### ISSUE TITLE
启动的时候提示failed to render pages

### ISSUE THREAD

**Issue by hillsbird** [xiaoheiAh/hugo-theme-pure#40]
报错信息：
Error: Error building site: failed to render pages: render of "section" failed: "/root/hillsbird/themes/hugo-theme-pure/layouts/_default/list.html:11:55": execute of template failed: template: _default/list.html:11:55: executing "content" at <$.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
这是啥意思？

**Comment by xiaoheiAh** [comment]
hugo 版本多少? 可能不能用

**Comment by hillsbird** [comment]
Hugo Static Site Generator v0.55.6-A5D4C82D linux/amd64 BuildDate: 2019-05-18T07:56:30Z

**Comment by xiaoheiAh** [comment]
@hillsbird 麻烦使用 0.57 以上的版本,`RegularPages ` 在这个版本开始有的
