### ISSUE TITLE
文章目录功能

### ISSUE THREAD

**Issue by befovy** [xiaoheiAh/hugo-theme-pure#41]
你好，这个 hugo 主题风格很好看，我很喜欢，谢谢你能够分享出来。

请问有没有计划实现文章目录功能？
比如这个 https://blog.befovy.com/2019/12/v2-go-modules/

如果不在计划中，可否指点一下应该如何修改，我前端完全是新手

**Comment by befovy** [comment]
刚才没有仔细看。

https://xiaohei.im/hugo-theme-pure/2019/11/event/ 是有文章目录功能的，谢谢。

请问如何在文章详情页默认右侧展示文章目录，而不是 【公告】【分类】【标签】等？ 谢谢

**Comment by xiaoheiAh** [comment]
nav.html line 19-29 替换成下面的.
```html
{{ with .Site.Params.config.toc }}
<li class="toggle-toc">
    <a class="toggle-btn" data-toggle="collapse" href="#collapseToc" aria-expanded="truer"
        title="{{ T "article_catalogue" }}" role="button">
        <span>[&nbsp;</span><span>{{ T "article_catalogue" }}</span>
        <i class="text-in icon icon-anchor"></i>
        <i class="text-collapsed icon icon-close"></i>
        <span>]</span>
    </a>
</li>
{{- end }}
```
sidebar-toc.html line2 的 `class` 去掉 `collapse`
```html
  <aside class="sidebar sidebar-toc " id="collapseToc" itemscope itemtype="http://schema.org/WPSideBar">
 ```

说实话这个目录我写的真丑,你有兴趣麻烦给美化下 😄 可以参考: [tocbot](https://github.com/tscanlin/tocbot)

**Comment by befovy** [comment]
谢谢，按照你的提示修改好了。
但是我还是暂时不用 toc 了，确实不好看，我也不会修改

**Comment by xiaoheiAh** [comment]
hi @befovy  我刚才改好了,你可以试用下

**Comment by befovy** [comment]
谢谢
