### ISSUE TITLE
当指定代码语言是会产生黑边

### ISSUE THREAD

**Issue by holtenko** [xiaoheiAh/hugo-theme-pure#42]
https://themes.gohugo.io//theme/hugo-theme-pure/post/markdown-syntax/
如下图所示
![image](https://user-images.githubusercontent.com/17680637/70500015-6e01c000-1b55-11ea-8f07-ff9d1cb224da.png)

**Comment by xiaoheiAh** [comment]
下面的使用 hugo 官方的 `highlight` shortcode, 没有对其做优化,也不建议使用.原生markdown语法即可.

**Comment by holtenko** [comment]
> 下面的使用 hugo 官方的 `highlight` shortcode, 没有对其做优化,也不建议使用.原生markdown语法即可.

如果使用原生markdown指定语言的话好像也会产生黑边
![image](https://user-images.githubusercontent.com/17680637/70503362-31869200-1b5e-11ea-91e4-31e75eae4b1a.png)
![image](https://user-images.githubusercontent.com/17680637/70503382-3b0ffa00-1b5e-11ea-9b57-91de43eb5e3c.png)
