### ISSUE TITLE
使用原生markdown在代码块中指定语言也会产生黑边

### ISSUE THREAD

**Issue by holtenko** [xiaoheiAh/hugo-theme-pure#43]
如果使用原生markdown指定语言的话好像也会产生黑边
![image](https://user-images.githubusercontent.com/17680637/70503362-31869200-1b5e-11ea-91e4-31e75eae4b1a.png)
![image](https://user-images.githubusercontent.com/17680637/70503382-3b0ffa00-1b5e-11ea-9b57-91de43eb5e3c.png)

**Comment by xiaoheiAh** [comment]
我倒是没有出现你这样的黑边 相同的代码
