### ISSUE TITLE
备案信息

### ISSUE THREAD

**Issue by SenLief** [xiaoheiAh/hugo-theme-pure#48]
您好，config.yml添加字段customFooter，但是备案信息并没有显示出来？

**Comment by xiaoheiAh** [comment]
@SenLief 没有这个字段吧.你是怎么加的?

**Comment by SenLief** [comment]
我在full-config里面看到的这个字段，那有什么办法添加吗？最近被打电话告诉加上。

发自我的华为手机


-------- 原始邮件 --------
发件人： "yx.z" <notifications@github.com>
日期： 2019年12月26日周四 晚上7:58
收件人： xiaoheiAh/hugo-theme-pure <hugo-theme-pure@noreply.github.com>
抄送： SenLief <zjanence@gmail.com>, Mention <mention@noreply.github.com>
主 题： Re: [xiaoheiAh/hugo-theme-pure] 备案信息 (#48)

@SenLief<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSenLief&data=02%7C01%7C%7C4e5a90e57ab741fc403108d789faddb9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637129582859116005&sdata=%2BnLSN0QGAP4Vvj4KTSfUqnb3YCKpPXFNPR%2Fw3rhBbVI%3D&reserved=0> 没有这个字段吧.你是怎么加的?

―

**Comment by xiaoheiAh** [comment]
@SenLief fork一份在[footer.html](https://github.com/xiaoheiAh/hugo-theme-pure/blob/master/layouts/partials/footer.html)里加一下你的代码好了.样式可以自己处理下
