### ISSUE TITLE
归档界面收缩bug

### ISSUE THREAD

**Issue by jiangfangzheng** [xiaoheiAh/hugo-theme-pure#50]
在归档界面，以你的demo为例子，就是  https://xiaohei.im/hugo-theme-pure/posts/   这个界面，如果文章的日期有2019年、2018年...，点击图标收缩，只有最上面的一个年份能收缩，而且是收缩全部年份的文章，点击2018年的图标，收缩功能无效。
![image](https://user-images.githubusercontent.com/8960834/71517469-1dc28600-28e9-11ea-8982-4e10d17338cc.png)

**Comment by xiaoheiAh** [comment]
感谢~我会调试修改下这个bug.修复了通知你.

**Comment by xiaoheiAh** [comment]
#58

**Comment by jiangfangzheng** [comment]
@xiaoheiAh 感谢及时修复，还有一个bug，修复后显示的日期每一篇都有年份
![image](https://user-images.githubusercontent.com/8960834/71589151-c4fc2300-2b5e-11ea-802e-461424a2eedd.png)

**Comment by jiangfangzheng** [comment]
@xiaoheiAh 我自己也[实现了一版](https://github.com/jiangfangzheng/hugo-theme-pure-mod/commit/78fddb3d51746fca7e12cbe25e1550304e310b84)，解决年份重复问题

**Comment by leonGravel** [comment]
> @xiaoheiAh 我自己也[实现了一版](https://github.com/jiangfangzheng/hugo-theme-pure-mod/commit/78fddb3d51746fca7e12cbe25e1550304e310b84)，解决年份重复问题

我觉得可以提一个PR，这个应该属于bug fix
