### ISSUE TITLE
tags do not wrap

### ISSUE THREAD

**Issue by ssbarnea** [xiaoheiAh/hugo-theme-pure#57]
It seems that the list of tags does not wrap, making the tags page look really broken. Obviously that this occurs only when you define more than a couple of tags. They should act as spans not as divs.

![tags-ss](https://sbarnea.com/ss/Screen-Shot-2019-12-30-10-33-51.png)

PS. Url of page `/tags/ansible-lint/`

**Comment by xiaoheiAh** [comment]
Sounds like you can fix it.Could you send a pr?My FE skills sucks.... 😷

**Comment by xiaoheiAh** [comment]
But when I test it,use 39 tags,It will show ellipsis
![image](https://user-images.githubusercontent.com/27981726/71579796-201b1f00-2b39-11ea-9e3f-40060f1d179f.png)

**Comment by ssbarnea** [comment]
I will make a PR as soon I finish more pressing issues (like migrating to hugo), that one not being a blocker. Not sure which browser you used but that happened to me with Firefox and Safari.

I have reasons to believe that this happens only when the right sidebar is enabled.
Something really fun, if I start resizing the window the eclipses appear but the default rendering of the page does not have eclipses. It may prove to be a complex CSS issue to solve.

PS. I am backend too, with only limited css experience.

**Comment by xiaoheiAh** [comment]
Thanks~ I use chrome.Use safari will reproduce it.
 By the way,Your profile is awesome!

**Comment by anbuchelva** [comment]
@ssbarnea can you check whether your issue is solved? After merging it?
