### ISSUE TITLE
list将content下所有文件都列出来了

### ISSUE THREAD

**Issue by dutzhang** [xiaoheiAh/hugo-theme-pure#70]
一般来讲，只希望列出来`/blog`或者`/post`文件夹下的内容，其它内容属于固定页面，不需要列出，也不需要评论框。

**Comment by ssbarnea** [comment]
While English is not my native language I do always file bugs in English, so others can read them. It would be really nice if the same would happen on hugo-theme-pure.

**Comment by xiaoheiAh** [comment]
use `mainSection` param
