### ISSUE TITLE
archive creates collection for current year only

### ISSUE THREAD

**Issue by smitphilip** [xiaoheiAh/hugo-theme-pure#73]
The archive page: all posts in the same year are grouped together

I started using your theme at the end of last year, and created a number of posts. in the new year, I've now created two more posts, and all posts from last year are each listed in their own group, and the 2 posts from this year are in the same group. 

If I change the posts from 2020 to drafts, all the posts from 2019 are all grouped together again. is this easily configurable from my side, or is this a change on the theme's side?

**Comment by xiaoheiAh** [comment]
@smitphilip posts are group by year.

**Comment by smitphilip** [comment]
![image](https://user-images.githubusercontent.com/42035621/71874902-bcda4f80-312b-11ea-9983-432dbd17dae7.png)

sure, this works... but as soon as there's a post from the current year, things get messed up.

![image](https://user-images.githubusercontent.com/42035621/71874970-e4311c80-312b-11ea-9434-b4877bbe98f0.png)

**Comment by xiaoheiAh** [comment]
@smitphilip already fixed.Please pull latest version.
