### ISSUE TITLE
toc: true不起作用

### ISSUE THREAD

**Issue by computbiol** [xiaoheiAh/hugo-theme-pure#79]
您好，非常喜欢您的主题。有个疑问，这样配置：
config:
    toc: true
文章目录好像没有作用，请问是还要配置其它地方吗？

**Comment by stefanJi** [comment]
<img width="341" alt="x" src="https://user-images.githubusercontent.com/15273198/78562134-77710f80-784b-11ea-8f33-53d7bcb283cc.png">

默认要点击底部的 Catalogue 才会显示，如果希望默认就显示可以参考我的改动，修改 `layouts/partials/sidebar-toc.html` 中第2行代码的样式为 `collapse`:

```html
class="sidebar sidebar-toc collapse in" id="collapseToc"
```

**Comment by LiangqinRen** [comment]
请问如何使侧边目录支持多级目录，目前没有查到如何支持多级目录，仅会显示最高级目录，而仅最高级目录可能很少，使得导航栏的作用大大下降。
