### ISSUE TITLE
在本地可以渲染成功，放在github page上就渲染不成功哎~

### ISSUE THREAD

**Issue by cenchaojun** [xiaoheiAh/hugo-theme-pure#82]
我可以在本地上渲染成功，但是部署到github page上就渲染不成功哎~这个是为啥呢~

**Comment by stefanJi** [comment]
你需要将 hugo 在 `public` 目录下生成的文件托管到 github page 对应的 repo 下

**Comment by xiaoheiAh** [comment]
推荐使用 github action 自动部署。很方便。[这里有介绍](https://blog.xiaohei.im/posts/github-action-guide/)

**Comment by huanggze** [comment]
大兄弟，我把 public 的内容放到 github page 对应的 repo 下了，还是渲染不正常。你了解咋回事吗？@stefanJi

![image](https://user-images.githubusercontent.com/22350668/83494227-893bff80-a4e8-11ea-9316-35b752b1b23f.png)

**Comment by huanggze** [comment]
浏览器报错
![image](https://user-images.githubusercontent.com/22350668/83494655-2dbe4180-a4e9-11ea-946f-5711fa586e07.png)

**Comment by huanggze** [comment]
解决了，还要修改 hugo config.yaml 里的 baseURL 参数
