### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by EightDouble2** [xiaoheiAh/hugo-theme-pure#84]
搜索是不是需要配置 搜索没有内容

**Comment by EightDouble2** [comment]
需要将`config.toml`删除`config.yml`才能生效

**Comment by heketong** [comment]
我删除了怎么也不起作用 本地预览的时候还是搜索不到什么内容

**Comment by EightDouble2** [comment]
你可以看下我的配置，我配置是成功了的
[https://github.com/EightDouble2/JBlog](https://github.com/EightDouble2/JBlog)

**Comment by EightDouble2** [comment]
> 我删除了怎么也不起作用 本地预览的时候还是搜索不到什么内容

你可以看下我的配置，我配置是成功了的
[https://github.com/EightDouble2/JBlog](https://github.com/EightDouble2/JBlog)
