### ISSUE TITLE
只有首页才被正常渲染的问题（含办法）

### ISSUE THREAD

**Issue by luodesinan** [xiaoheiAh/hugo-theme-pure#9]
@xiaoheiAh 
具体说应该不能叫做问题，是一个新手很有可能犯的小差错。
具体情况如下
> 在把themes中exampleSite中的config.yml文件覆盖到站点根目录后，如果直接hugo -t pure 命令渲染的话会出现只有站点的首页才被正确渲染，而其他链接点击后可以跳转但是页面没有被完整渲染。

解决方法如下
> 把复制出来的config文件中第一行中的  bashURL: http://example.com/    改为   bashURL: /   保存后重新渲染一边即可解决。希望作者能把这个提示也加在readme.md 的两个版本中，后来者也能少走弯路

最后，感谢作者的辛苦付出~ 👍

**Comment by xiaoheiAh** [comment]
我这边没有复现你的问题.是否还有其他的设置项干扰了?

**Comment by luodesinan** [comment]
> 我这边没有复现你的问题.是否还有其他的设置项干扰了?

我不知道是不是因为我是用的Nginx做web服务器(只把hugo当渲染器啦)，我查找资料的时候也有看到有些人在hugo server 中是没有问题的，但是在Nginx中就会有问题。
感谢回复 and 你的Blog记录得很好诶nice 💯

**Comment by xiaoheiAh** [comment]
谢谢~我也是刚开始 😃

**Comment by xiaoheiAh** [comment]
> > 我这边没有复现你的问题.是否还有其他的设置项干扰了?
> 
> 我不知道是不是因为我是用的Nginx做web服务器(只把hugo当渲染器啦)，我查找资料的时候也有看到有些人在hugo server 中是没有问题的，但是在Nginx中就会有问题。
> 感谢回复 and 你的Blog记录得很好诶nice 💯

理论上如果用nginx代理的话应该是要将 `basrURL` 设置到 `/`,转发的时候才能进来
